export const USER_LOGIN_SUCCESS = "USE_LOGIN_SUCCESS";
export const USER_LOGIN_REQUEST = "USE_LOGIN_REQUEST";
export const USER_LOGIN_FAIL = "USE_LOGIN_FAIL";
export const USER_LOGOUT = "USE_LOGOUT";

export const USER_REGISTER_SUCCESS = "USE_REGISTER_SUCCESS";
export const USER_REGISTER_REQUEST = "USE_REGISTER_REQUEST";
export const USER_REGISTER_FAIL = "USE_REGISTER_FAIL";

export const USER_DETAILS_SUCCESS = "USE_DETAILS_SUCCESS";
export const USER_DETAILS_REQUEST = "USE_DETAILS_REQUEST";
export const USER_DETAILS_FAIL = "USE_DETAILS_FAIL";

export const USER_UPDATE_PROFILE_SUCCESS = "USE_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_REQUEST = "USE_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_FAIL = "USE_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USE_UPDATE_PROFILE_RESET";
